package by.thmihnea.cooldown;

public enum CooldownType {
    FROM_THE_ASHES,
    REINCARNATION,
    NATURES_DEFENSE,
    FLUTTER,
    LAST_STING,
    COCOON,
    QUICK_STRIKE,
    MIGHTY_STALLION,
    RESOLUTE_STANCE,
    STALEMATE,
    QUEENS_GAMBIT,
    STURDY,
    HOMERUN,
    PICKPOCKET,
    HEAL,
    GREATER_GOOD,
    SHURIKEN,
    RIDER,
    BLIND,
    SNEAK,
    ENTANGLEMENT,
    HIDDEN_SHADOWS,
    METEOR_SHOWER,
    JUSTICE,
    CYCLICAL_CUTS
}
